import type { Prisma } from '@prisma/client';

/**
 * Every `Location` scalar except `brandFilterMode`, for databases that have not run the migration yet.
 */
export const locationScalarSelectWithoutBrandFilterMode = {
  id: true,
  uploadId: true,
  handle: true,
  name: true,
  status: true,
  addressLine1: true,
  addressLine2: true,
  postalCode: true,
  city: true,
  stateProvinceRegion: true,
  country: true,
  phone: true,
  email: true,
  website: true,
  imageUrl: true,
  monday: true,
  tuesday: true,
  wednesday: true,
  thursday: true,
  friday: true,
  saturday: true,
  sunday: true,
  latitude: true,
  longitude: true,
  pageTitle: true,
  pageDescription: true,
  metaTitle: true,
  metaDescription: true,
  priority: true,
  tags: true,
  brands: true,
  customBrands: true,
  isPremium: true,
  nameEn: true,
  addressLine1En: true,
  cityEn: true,
  nameFr: true,
  pageTitleFr: true,
  pageDescriptionFr: true,
  customBrandsFr: true,
  nameZhCn: true,
  pageTitleZhCn: true,
  pageDescriptionZhCn: true,
  customBrandsZhCn: true,
  nameEs: true,
  pageTitleEs: true,
  pageDescriptionEs: true,
  customBrandsEs: true,
  customButton1Title: true,
  customButton1Url: true,
  customButton2Title: true,
  customButton2Url: true,
  customButton1TitleFr: true,
  customButton1UrlFr: true,
  customButton1TitleZhCn: true,
  customButton1UrlZhCn: true,
  customButton1TitleEs: true,
  customButton1UrlEs: true,
  customButton2TitleFr: true,
  customButton2UrlFr: true,
  customButton2TitleZhCn: true,
  customButton2UrlZhCn: true,
  customButton2TitleEs: true,
  customButton2UrlEs: true,
  createdAt: true,
  updatedAt: true,
} as const satisfies Prisma.LocationSelect;
